### ISSUE TITLE
Potential Typo "Modular Avater"

### ISSUE THREAD

**Issue by Spokeek** [Azukimochi/LLC-Docs#2]
I may be wrong or that could be due to language barrier, but shouldn't "Modular Avater" be "Modular Avatar" ?

Tell me.

**Comment by Azukimochi** [comment]
Thank you for tell me.
All except "Modular Avatar" are typos. I'm currently rebuilding most of the page, so I'll fix it. thank you

**Comment by Spokeek** [comment]
Also not related to the issue, but i looked at your project because it got recommended for my MA Package List i made, and that's a really cool tool you have, gotta say 👑 
If you wanna look 
https://github.com/Spokeek/awesome-ndmf?tab=readme-ov-file#light-limit-changer
You can thank [Sayamame-beans](https://github.com/Sayamame-beans)

**Comment by Azukimochi** [comment]
The page has been significantly revised and the typo in "Avater" has also been corrected.

It looks like a very useful list of NDMF tools. We hope that it will spread to users overseas.
And I would like to thank my friend Syamame-beans.
thank you

**Comment by Spokeek** [comment]
If it needs maybe could translate it if that can help spread it around.
